version: '3.8'

services:
  app:
    image: ${DOCKERHUB_USERNAME}/stockscope:${ENV}
    container_name: stockscope
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=${ENV}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_REDIS_HOST=redis
    depends_on:
      - db
      - redis
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: stockscope-db
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: stockscope-redis
    restart: unless-stopped

volumes:
  postgres_data: