spring:
  application:
    name: stockscope
    
  profiles:
    active: local
  
  jpa:
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

logging:
  level:
    me.hyeonjae.stockscope: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE