spring:
  application:
    name: stockscope
    
  profiles:
    active: test
  
  datasource:
    url: jdbc:postgresql://localhost:5432/stockscope
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false
    
  redis:
    host: localhost
    port: 6379

logging:
  level:
    me.hyeonjae.stockscope: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE