spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  
  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  redis:
    host: localhost
    port: 6379