name: CI/CD Pipeline

on:
  push:
    branches:
      - "main"
      - "release/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      
      - name: Build and Test
        run: ./gradlew clean build

      # 빌드 결과물 저장
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: build/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 빌드 결과물 다운로드
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts
          path: build/

      # 파일 위치 확인 (디버깅용)
      - name: List files
        run: ls -R build/
      
      # 브랜치에 따라 다른 환경에 배포
      - name: Set environment
        id: set-env
        run: |
          if [[ ${{ github.ref }} == 'refs/heads/main' ]]; then
            echo "ENV=prod" >> $GITHUB_OUTPUT
          else
            echo "ENV=stage" >> $GITHUB_OUTPUT
          fi
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Docker Buildx 설정 추가
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # 브랜치별로 다른 태그 사용
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/stockscope:${{ steps.set-env.outputs.ENV }}
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/stockscope:${{ steps.set-env.outputs.ENV }}
          cache-to: type=inline
      
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          # 브랜치별로 다른 EC2 인스턴스 사용
          host: ${{ steps.set-env.outputs.ENV == 'prod' && secrets.PROD_EC2_HOST || secrets.STAGE_EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/stockscope:${{ steps.set-env.outputs.ENV }}
            docker stop stockscope || true
            docker rm stockscope || true
            docker run -d --name stockscope \
              -p 8080:8080 \
              -e SPRING_PROFILES_ACTIVE=${{ steps.set-env.outputs.ENV }} \
              --restart unless-stopped \  # 컨테이너 자동 재시작 설정
              ${{ secrets.DOCKERHUB_USERNAME }}/stockscope:${{ steps.set-env.outputs.ENV }}