# 1. 워크플로우 이름 설정
name: Java CI with Gradle

# 2. 워크플로우 트리거 설정
on:
  push:
    branches: [ "*" ]  # 모든 브랜치에 대해 동작
  pull_request:
    branches: [ "*" ]  # 모든 브랜치에 대해 동작

# 3. 권한 설정
permissions:
  contents: read # 레포지토리 컨텐츠에 대한 읽기 권한만 설정

# 4. 작업(jobs) 정의
jobs:
  build: # build 라는 이름의 job
    runs-on: ubuntu-latest # ubuntu 최신 버전에서 실행
    
    steps: # 실행할 단계들
    # 5. 소스코드 체크아웃
    - uses: actions/checkout@v4
    
    # 6. JDK 21 설정
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin' # Eclipse Temurin JDK 사용
        
    # 7. Gradle 설정
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    
    # 8. Gradlew 실행 권한 부여
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    # 9. Gradle 빌드 실행
    - name: Build with Gradle
      run: ./gradlew clean build
      
    # 10. 테스트 실행
    - name: Test with Gradle
      run: ./gradlew test
      
    # 11. 테스트 결과 업로드
    - name: Upload test results
      if: success() || failure() # 테스트 성공/실패 상관없이 실행
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: build/reports/tests/test/ # 테스트 결과 저장 경로
        
    # 12. 코드커버리지 리포트 업로드
    - name: Upload coverage reports
      if: success() # 테스트 성공 시에만 실행
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # Codecov 토큰 설정
        files: ./build/reports/jacoco/test/jacocoTestReport.xml  # Jacoco 리포트 파일